/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlythuphidichvucanho.view;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author PC
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnChooseSpecialPerson = new javax.swing.JButton();
        btnChooseResidents = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html>Quản lý tình hình dân cư<br> ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(960, 679));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnChooseSpecialPerson.setBackground(new java.awt.Color(0, 0, 102));
        btnChooseSpecialPerson.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnChooseSpecialPerson.setForeground(new java.awt.Color(255, 255, 255));
        btnChooseSpecialPerson.setText("<html><div style='text-align: center;'>Quản lý dịch vụ<br></div>");
        btnChooseSpecialPerson.setToolTipText("");
        btnChooseSpecialPerson.setBorder(null);
        btnChooseSpecialPerson.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChooseSpecialPerson.setOpaque(true);
        btnChooseSpecialPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseSpecialPersonActionPerformed(evt);
            }
        });
        getContentPane().add(btnChooseSpecialPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 800, 87));

        btnChooseResidents.setBackground(new java.awt.Color(0, 0, 102));
        btnChooseResidents.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnChooseResidents.setForeground(new java.awt.Color(255, 255, 255));
        btnChooseResidents.setText("<html><div style='text-align: center;'>Quản lý thông tin khách hàng<br></div>");
        btnChooseResidents.setToolTipText("");
        btnChooseResidents.setBorder(null);
        btnChooseResidents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChooseResidents.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChooseResidents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseResidentsActionPerformed(evt);
            }
        });
        getContentPane().add(btnChooseResidents, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 800, 87));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("<html>       Quản lý căn hộ<br> ");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 240, 105));

        jLabel9.setIcon(new ImageIcon("src/main/java/com/mycompany/quanlydoituongdacbiet/view/Lovepik_com-500330964-blue-blazed-background.jpg"));
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 629, 311, 642));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseSpecialPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseSpecialPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChooseSpecialPersonActionPerformed

    private void btnChooseResidentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseResidentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChooseResidentsActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }
    
    public void addChooseSpecialPersonListener(ActionListener listener){
        btnChooseSpecialPerson.addActionListener(listener);
    }
    
    public void addChooseResidentsListener(ActionListener listener){
        btnChooseResidents.addActionListener(listener);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseResidents;
    private javax.swing.JButton btnChooseSpecialPerson;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
